[kpi.server]
# asgi = "uvicorn"
asgi = "hypercorn"
# host-binding = "0.0.0.0"
port = 8003

[kpi.db]
dialect = "postgresql"
username = "kpi_db_user"
name = "kpi_db"
password = "GentleCorp16.04.2025"
password-admin = "#3]O?4RGj)DE7Z!9SA5"
username-admin = "bn_keycloak"
host = "localhost"
# locust: auskommentieren
log-statements = true

[kpi.dev]
# z.B. DB neu laden
enabled = true

[kpi.excel]
enabled = true

[kpi.graphql]
# locust: auskommentieren
graphiql-enabled = true

[kafka]
bootstrap-servers = "localhost:9092"
topic_customer_created = "customer.created"
topic_order_completed = "order.completed"
topic_transaction_created = "transaction.created"
topic_product_moved = "product.moved"
